export const REPOSITORY_URL =
  'https://github.com/Pierre-MarieMarchio/ngx-statewise';
export const NPM_URL = 'https://www.npmjs.com/package/ngx-statewise';

/**
 * Where the site is served from. Used for the absolute `hreflang` and
 * canonical URLs, which search engines want fully qualified.
 */
export const SITE_URL = 'https://pierre-mariemarchio.github.io/ngx-statewise';

/** The published changelog, generated by release-it from the commit history. */
export const CHANGELOG_URL = `${REPOSITORY_URL}/blob/main/projects/ngx-statewise/CHANGELOG.md`;

/**
 * The whole public API, bundled, minified and gzipped, in kilobytes.
 *
 * A number on a page rots the moment the library grows, so this one is checked
 * rather than trusted: `npm run verify:size` rebuilds the measurement from
 * dist/ngx-statewise and fails if it no longer rounds to this value. It runs in
 * `npm run check`, right after the library is built.
 */
export const LIBRARY_GZIP_KB = 2.7;
