export const REPOSITORY_URL =
  'https://github.com/Pierre-MarieMarchio/ngx-statewise';
export const NPM_URL = 'https://www.npmjs.com/package/ngx-statewise';

/**
 * Where the site is served from. Used for the absolute `hreflang` and
 * canonical URLs, which search engines want fully qualified.
 */
export const SITE_URL = 'https://pierre-mariemarchio.github.io/ngx-statewise';

/** Where release-it publishes each tag. */
export const RELEASES_URL = `${REPOSITORY_URL}/releases`;

/**
 * The published version of the library, shown beside the wordmark.
 *
 * Checked rather than trusted, like the size below it: `npm run verify:claims`
 * reads projects/ngx-statewise/package.json and fails if the two disagree, so
 * a release that forgets this line does not ship a site claiming the old one.
 */
export const LIBRARY_VERSION = '0.6.4';

/** The published changelog, generated by release-it from the commit history. */
export const CHANGELOG_URL = `${REPOSITORY_URL}/blob/main/projects/ngx-statewise/CHANGELOG.md`;

/**
 * The whole public API, bundled, minified and gzipped, in kilobytes.
 *
 * A number on a page rots the moment the library grows, so this one is checked
 * rather than trusted: `npm run verify:claims` rebuilds the measurement from
 * dist/ngx-statewise and fails if it no longer rounds to this value. It runs in
 * `npm run check`, right after the library is built.
 */
export const LIBRARY_GZIP_KB = 4.7;
