name: Automatic Versioning

on:
  push:
    branches: [main, next]
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.13.1"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm ci
          npm install -g @angular/cli
          
      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: Determine changed libraries
        id: changed-libs
        run: |
          npx lerna changed --json > changed-libs.json
          cat changed-libs.json
          echo "changed_libraries=$(cat changed-libs.json | jq -r '.[].name' | paste -sd ',' -)" >> $GITHUB_ENV

      - name: Run versioning script
        run: |
          node .scripts/versioning.js

      - name: Build changed libraries
        run: node .scripts/build-changed-libs.js

      - name: Publish changed libraries to NPM
        run: node .scripts/publish-changed-libs.js
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
