name: Automatic Versioning

on:
  push:
    branches: [main, next]
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.13.1"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm ci
          npm install -g @angular/cli
          
      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: Determine changed libraries
        id: changed-libs
        run: |
          node .scripts/determine-changed-libs.js
          echo "changed_libraries=$(cat changed-libs-output.txt)" >> $GITHUB_OUTPUT

      - name: Run versioning script
        if: steps.changed-libs.outputs.changed_libraries != ''
        run: |
          node .scripts/versioning.js

      - name: Build changed libraries
        if: steps.changed-libs.outputs.changed_libraries != ''
        run: node .scripts/build-changed-libs.js

      - name: Set up NPM auth
        if: steps.changed-libs.outputs.changed_libraries != ''
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish changed libraries to NPM
        if: steps.changed-libs.outputs.changed_libraries != ''
        run: node .scripts/publish-changed-libs.js

